### PR TITLE
Improve the way we ask users for their contact details

### PR DESCRIPTION
**Pull request by suryanaga**
This affects both concessionary travel and parking permits, making the contact details flow consistent across both.

We now don't give users an explicit option for no confirmation message, because of #185.

Radio buttons have been changed to checkboxes because of #186, #187, #188, and #236.

## Before

This was inconsistent in loads of places before, but the basic pattern was something like this:

screen shot 2017-03-23 at 12 56 16

It was also inconsistent in the flow and linked to from the success page.

## After

screen shot 2017-03-23 at 12 52 50
screen shot 2017-03-23 at 12 53 11

### CODE REVIEW

**Comment by kaydale** [comment]
@sanjaypoyzer Hypothetically all fine. 

But what is the plan for this on the confirmation page at the end of the applications 

screen shot 2017-03-24 at 12 53 00


atm it links though to the old style radio buttons.

**Comment by suryanaga** [comment]
@kaydale I'm confused as to how you've got to that, I can't find "About your pass" - You sure you've pulled the latest version?

**Comment by kaydale** [comment]
@sanjaypoyzer 
#cringe 

I had not :(

**Comment by anthonylord** [comment]
For the 'Confirmation messages' page, let's try this.


We send you a message:
- with your reference number
- when your resident's parking permit is on its way

**Comment by anthonylord** [comment]
The renewal notification page is for parking permits, but talks about '5 years'. This should be '1 year'.
Also, can you delete the 'also' in the first sentence?

**Pull request merged**
