### PR TITLE
PR: reducing reuse Verify service links

### PR DESCRIPTION
**Pull request by lizziebruce**
Resolution for issue #326 

Before:
screen shot 2017-05-19 at 16 34 26

After:

screen shot 2017-05-19 at 16 31 08

### CODE REVIEW

**Review by suryanaga — APPROVED** [review]

**Review by ghost — APPROVED** [review]
Looks good, nothing broke, merging!

**Comment by ghost** [comment]
@lizziebruce do we want to do this for the CT page as well?

**Comment by lizziebruce** [comment]
@samuelculley we'll also reduce the reuse Verify service links on CT, but different links will be kept... discussion is in #471 @irinapencheva @sanjaypoyzer

**Comment by ghost** [comment]
@lizziebruce ah perfect, didn't spot that one

**Pull request merged**
