### PR TITLE
PR: Oxfordshire account

### PR DESCRIPTION
**Pull request by suryanaga**
Addresses #660 

This is to test what would happen if Oxfordshire matches a Verified user to an existing Oxfordshire account.

There are two versions of this to test:

## "Invisible" account

image

## "Visible" account

image

@abibarkeroxfordshire Is this content consistent with Oxfordshire's website? (Especially the visible account one?)

@lizziebruce Any feedback on the content here?

### CODE REVIEW

**Comment by EUzkuraityte** [comment]
@sanjaypoyzer To make the messaging more consistent between the two versions, could we not say for the 'visible' account - 'We've found the following details in your Oxfordshire account'. Technically there isn't any logging in happening, just data matching in the background.

**Comment by lizziebruce** [comment]
Screen 1.
Before
Information you enter in this service will also be stored in our system for use in future services.

After

> Information you enter for this service will be kept and used next time you access one of our services online. Data will be securely stored in our system.

Screen 2. 
Before
We’ve automatically logged you in to your Oxfordshire account and found the following details:

After

> We've found the following details from your Oxfordshire County Council account:


> Information you enter for this service will be kept and used next time you access one of our services online. Data will be securely stored in our system.

**Review by lizziebruce — CHANGES_REQUESTED** [review]
Please see content suggestions in comment.

**Comment by suryanaga** [comment]
@lizziebruce's changes made. @abibarkeroxfordshire to also approve.

**Review by lizziebruce — APPROVED** [review]

**Comment by suryanaga** [comment]
@abibarkerOxfordshire, could you take a look at this and let me know if it's all good?

**Comment by AbiBarkerOxfordshire** [comment]
@sanjaypoyzer All looks good thanks...

**Pull request merged**
