### PR TITLE
Improve the way we get people to choose verify

### PR DESCRIPTION
**Pull request by suryanaga**
Addresses #194. 

This aims to make the page previously titled "Verifying your identity" much clearer, by giving users a clear choice of using Verify or not and also explaining what the consequences of those choices are.

It includes an extra page for giving consent for data to be used.

It also works the same on both services. (With slightly modified content.)

[Slides showing other iterations I tried on this](https://docs.google.com/a/digital.cabinet-office.gov.uk/presentation/d/1xL9vh3SoXQ5LoAheqdSlYQDB_wNgCvCrsHUnzFQzlAo/edit?usp=sharing). (Accessible through GDS google accounts only)

**Before**

screen shot 2017-03-08 at 15 16 57

**After**

PP:
screen shot 2017-03-13 at 17 14 28
(Scan / upload goes to the nonverify start page, verify goes to this next screen...)

screen shot 2017-03-13 at 17 17 38
(Yes goes to Verify, No goes to the nonverify start page)

CT:
screen shot 2017-03-13 at 17 18 23

screen shot 2017-03-13 at 17 18 56

### CODE REVIEW

**Comment by anthonylord** [comment]
Claim your... pages:

- [x] 'in 5 working days' and 'in 10 working days' are exact statements. Let's try 'within 5 working days' and 'within 10 working days' 
- [ ] Some users won't be asked identity questions, so replace the To sign up message with the standard message we use on GOV.UK start pages: 'If you haven’t used GOV.UK Verify before, it takes about 15 minutes to get set up.' 
- [x] The H1 for the parking permit page should include 'parking', so 'Claim your parking permit' 
- [x] Change 'You'll need to upload and scan two documents' to 'You need to scan and upload 2 documents'

Your personal data pages:

- [x] 'via' isn't plain English, replace with 'with'
- [x] 'whilst' isn't plain English, replace with 'when'
- [x] the PP version doesn't have DoB, do they not need this part of the matching data set?
- [x] the PP version calls the thing a 'resident's parking permit', but the previous page has it as 'parking permit'. We must be consistent
- [x] the CT version calls the thing an 'older person's bus pass', but the previous page has it as a 'bus pass'. We must be consistent
- [x] users won't sign in on the next screen, if they already have an identity account it will be 3 screens until they can sign in. So let's try researching something like this:

The only information GOV.UK Verify will share with Argleton County Council is your:
- name
- address
- date of birth

**Comment by suryanaga** [comment]
@anthonylord Agreed on all of that except: 

> - Some users won't be asked identity questions, so replace the To sign up message with the standard message we use on GOV.UK start pages: 'If you haven’t used GOV.UK Verify before, it takes about 15 minutes to get set up.'


Aren't all pages in IDP journeys essentially identity questions? "Enter your bank details" for example is essentially an identity question; a question asked to prove your identity. Definitely recognise it doesn't feel as much like a question as the knowledge based ones, but I want to try this wording to try and explain better what's actually happening, ie the user is being tested on their identity. Does that make sense?

**Comment by suryanaga** [comment]
Oh and yeah, PP doesn't need DoB. :)

**Comment by anthonylord** [comment]
@sanjaypoyzer 
Always happy to test (nearly) everything and anything, so sure, go for it. Ask Pete to focus on that sentence please, what do users expect the questions will be. Looking forward to the feedback as it's something we haven't tried before.
Used to debate this with Joe a couple of years ago. I'm of the opinion that 'enter bank details' and  'download an add and take a photo of your passport', for example, aren't identity questions, they aren't even worded as questions. But broadly speaking they are part of the identity verification process, so maybe users will see them as questions.

**Comment by petegale** [comment]
@anthonylord @sanjaypoyzer Really keen to see how users respond to this, it also feels like it may give a more informed decision. I'll happily focus on this in our next round of testing. I won't ask what they expect the questions will be, as I'm not sure that's the key here, rather I'll focus on their ability to make the right choice for them at this point, and whether the way that decision is framed here causes issues later.

**Comment by kaydale** [comment]
screen shot 2017-03-20 at 14 36 47

When I tested the non verify route the confirmation page says I will get my pass within 5 days & I think It should be 10 days right?

**Comment by suryanaga** [comment]
@kaydale We're not testing that route at the moment. I think that issue is out of scope for this pull request, but have just created a seperate issue for it. #248

**Comment by kaydale** [comment]
@sanjaypoyzer fair enough - merging now.

**Pull request merged**
