### PR TITLE
Feature/prove vehicle ownership

### PR DESCRIPTION
**Pull request by Artgov**
The page below was the starting page and I add extra if statement for Oxfordshire

entering point

If the address is correct then you will get to the page below

firstpage

If option Not was chosen then you will get the following

f-no-vehicle-ownership

If car been given by employer then you will go to pages where you will upload two documents V5 and employer's confirmation letter

if-my-employer-upload-v5

if-yes-upload-letter-from-your-employer

if rented

if-rented-vehicle

If new

if-new-vehicle

If you car owner you will be going to v5 uploading page

#659 

if-yes-uploadv5
if-yes-uploadv5-end

Prove vehicle ownership pages have been done, a bit in  hurry so please let me know if I will need to adjust it

@sanjaypoyzer 
@lizziebruce

### CODE REVIEW

**Comment by AbiBarkerOxfordshire** [comment]
@Artgov On the 'Do you own your vehicle or is it a company car?' I think we need different options from Yes or No - we either need to change the question to 'Do you own your vehicle' and leave it as Yes or No, or keep the question the same and change the answers to I own my vehicle or I do not own my vehicle? @sanjaypoyzer @lizziebruce - does that sound ok?

**Comment by lizziebruce** [comment]
@AbiBarkerOxfordshire @Artgov @sanjaypoyzer The question should just be "Do you own the vehicle?" and left as Yes or No. This better accommodates users with cars they rent themselves.

**Comment by lizziebruce** [comment]
@AbiBarkerOxfordshire @Artgov @sanjaypoyzer 

Further feedback on content page by page below.

**Vehicle ownership** - remove ? from title

**Vehicle ownership document**

New copy:

> Upload a photo or scan of 1 of the following:
> 
> - first page of the V5C vehicle registration certificate document, also known as a logbook
> - lease agreement registered to your employer
> 
> Take the photo with a smartphone or digital camera or scan using a document scanner.

Button text: [Upload]


**Letter from your employer**

Remove colon after the word “car” and replace with a full stop.

Delete: “Upload a photo or scan of the first page of a letter from your employer.”

Button text: [Upload]


**Rented vehicle**

Remove colon after the word “yourself” and replace with a full stop.

Button text: [Upload]


**New vehicle**

Remove colon after the word “name” and replace with a full stop.

Button text: [Upload]


**Upload your V5C**

Button text: [Upload]

**Comment by Artgov** [comment]
@AbiBarkerOxfordshire @lizziebruce  @sanjaypoyzer

Here are the changes been done

**Comment by lizziebruce** [comment]
@Artgov @AbiBarkerOxfordshire Hi Arty, thanks for these updates. Just one thing, on the Vehicle ownership document page please delete the line after the bullet points:

"Upload a photo or scan of the first page of V5C vehicle registration certificate. It's also known as a logbook."

because it duplicates the copy in the first bullet point.

After that it's ready merge!

**Comment by Artgov** [comment]
@AbiBarkerOxfordshire @lizziebruce 
Hi Lizzie the changes are done, I think its ready to merge

**Comment by AbiBarkerOxfordshire** [comment]
@sanjaypoyzer Do you know what this error is? Is it something we should fix at our end? Thanks!

**Review by suryanaga — APPROVED** [review]

**Comment by suryanaga** [comment]
@AbiBarkerOxfordshire All looks fine to me :)

**Pull request merged**
