### PR TITLE
Verify Prototype changes for Sunderland City Council

### PR DESCRIPTION
**Pull request by kenmaddison-scc**
Additions to Verify Parking Prototyping for Sunderland City Council

### CODE REVIEW

**Comment by suryanaga** [comment]
@kenmaddison-scc Many thanks for this (and well done on being first 🎉)!

I've added [a pull request](https://github.com/kenmaddison-scc/verify-local-patterns/pull/1) to your fork. Feel free to merge or close it. I'll wait for you to look at that before merging this.

This has also flagged up a bug, where the prototype breaks if the first permit option cost is 0/free. [I've added an issue for that here](https://github.com/alphagov/verify-local-patterns/issues/242) and I'll fix that before we merge this in so we can review those pages too.

**Comment by suryanaga** [comment]
@kenmaddison-scc Would also be really great if you could edit `lib/sunderland_template.html` to include more of what's in Sunderland's header. (Image below) There's good possibility we might see people click some of those links in testing, especially the more relevant ones like "Residents". You don't need to make them work (although you could make them link to the live URLs if you want), would just be great to get it looking as accurate as possible for testing.

screen shot 2017-03-16 at 14 51 20

**Comment by suryanaga** [comment]
Thanks @kenmaddison-scc, have added another PR to your repo here - https://github.com/kenmaddison-scc/verify-local-patterns/pull/2

**Comment by kenmaddison-scc** [comment]
Thanks Sanjay

**Comment by suryanaga** [comment]
Great work! You can now switch the prototype to your version at https://verify-local-patterns.herokuapp.com/council-picker :)

**Pull request merged**
