### PR TITLE
PR: Adding privacy copy line to vehicle reg number page

### PR DESCRIPTION
**Pull request by lizziebruce**
Pull Request for #452 "Users need to know how the council will be storing their vehicle registration data"

Before
screen shot 2017-05-12 at 15 23 04

After
screen shot 2017-05-12 at 15 23 12

### CODE REVIEW

**Review by suryanaga — APPROVED** [review]

**Comment by lizziebruce** [comment]
As above for V5c page:

Before
screen shot 2017-05-12 at 15 19 11

After
screen shot 2017-05-12 at 15 52 52

**Review by EUzkuraityte — APPROVED** [review]

**Comment by EUzkuraityte** [comment]
@lizziebruce looks good to me! I will circulate this to LAs to be checked if this is factually correct. I don't foresee there being any changes, but just want to be sure as some of them have v complicated   relationships with their suppliers.

**Comment by suryanaga** [comment]
@EUzkuraityte Ok to merge this or should I wait for confirmation from you?

**Comment by EUzkuraityte** [comment]
@sanjaypoyzer yup, merge this please

**Pull request merged**
