### PR TITLE
PR: copy re-scope for resident's start page

### LINKED ISSUE #313: Users need to know how their permit price is determined
@sanjaypoyzer content on this page:

https://verify-local-patterns.herokuapp.com/service-patterns/parking-permit/example-service/resident-start

does not tell the user how the permit price is determined (and that was something that users wanted to know, it came out from our lab day)

### PR DESCRIPTION
**Pull request by lizziebruce**
Resolves #313 Users need to know how their permit price is determined

@sanjaypoyzer I'll need your help creating the localisation rules for the copy in square brackets.

Before
screen shot 2017-05-10 at 15 48 54

After
screen shot 2017-05-10 at 18 05 47

### CODE REVIEW

**Review by EUzkuraityte — APPROVED** [review]

**Comment by lizziebruce** [comment]
@sanjaypoyzer hi did you see this one? It's the page you and @EUzkuraityte were happy with yesterday except with the Verify-related content moved out. Would be great to get this flowing through so we have an updated prototype for Monday's testing! @petegale is aware this is likely to be coming through.

**Comment by suryanaga** [comment]
@lizziebruce Yep, gonna go through and add the conditional logic.

**Comment by suryanaga** [comment]
Just a note on "What you'll need" - The first and 4th bullet points are essentially talking about what you need for Verify, and possibly imply needing documents the user won't need. I'm happy to merge this in though and see what users interpret it as. (cc @petegale)

screenshot-localhost-3000 2017-05-11 17-02-49

**Comment by lizziebruce** [comment]
@sanjaypoyzer @petegale Do you mean non-Verify? This isn't the case either way. Bullet point 1 was previously for document upload e.g. "documents to prove.." and I edited to "ability to prove.." on Egle's advice so that it applied for both doc upload and Verify. Bullet point 2 is clearly for both: answer security questions or upload documents.

**Pull request merged**
