### PR TITLE
Remove 6 month as an option

### LINKED ISSUE #261: Remove 6 month permit (council option)
Some councils do not offer 6 month permits.

### PR DESCRIPTION
**Pull request by suryanaga**
Adds a council option to remove 6 month permits.

Fixes #261.

---

### Before
screen shot 2017-03-31 at 10 56 14

### After
screen shot 2017-03-31 at 10 55 25

## Enter reg

This page is the same _except_ the button links to a different page based on the council options. If `sixmonth` is false and the council only has one cost, there's no choice for the user to make so they go straight to the "Choose a start date" page. 

screen shot 2017-03-31 at 17 16 27

## Choose a permit

2 different options affect this flow:

 - DVLA API (currently on for councils with more than 1 price of permit)
 - `6month`

## `6 month: true` + no DVLA API

screen shot 2017-03-31 at 16 02 07

## `6month: false` + DVLA API

screen shot 2017-03-31 at 15 59 43

## `6 month: true` + DVLA API

screen shot 2017-03-31 at 15 58 21

## `6 month: false` + no DVLA API

If they only have one cost of permit, and they don't offer 6 month permits, then it skips the page, as mentioned above.

### CODE REVIEW

**Comment by suryanaga** [comment]
@kaydale I think this is done, but it's quite a complex one so let me know when you're free and we'll have a look at it together.

**Comment by kaydale** [comment]
@sanjaypoyzer would be good to go through it together are you free on Wednesday to go through it together?

**Comment by suryanaga** [comment]
@kaydale I'll calendar you

**Comment by suryanaga** [comment]
TO DO: Document properly in pattern text.

**Comment by suryanaga** [comment]
screen shot 2017-04-06 at 15 54 29

@kaydale lol I forgot i already added this to the pattern text.

If you're happy that that clearly talks about what we looked at together, then this is ready to merge.

**Pull request merged**
