### PR TITLE
Improved flow for uploading a photo

### PR DESCRIPTION
**Pull request by suryanaga**
Aims to address #202, and also hopefully #201, #200, #203, #204. 

Kind of hard to properly illustrate the flow with just screenshots, but ah well.

## Before

screenshot-verify-local-patterns herokuapp com 2017-03-20 11-58-34
screen shot 2017-03-20 at 11 59 17
screen shot 2017-03-20 at 11 59 40

## After

screenshot-localhost-3000 2017-03-20 12-03-58

 - If has photo, then:
screenshot-localhost-3000 2017-03-20 12-05-11

 - else if no or not sure then:

screen shot 2017-03-20 at 12 06 30

 - If has camera, then 
screenshot-localhost-3000 2017-03-20 12-07-13

(Big green button on above screen routes to upload page)

 - else if no camera
screen shot 2017-03-20 at 12 09 33

After user uploads a photo, they see this screen:

screenshot-localhost-3000 2017-03-20 12-11-53

### CODE REVIEW

**Comment by kaydale** [comment]
screen shot 2017-03-20 at 14 57 49

Weirdness when clicking the "get help with uploading a file"

**Comment by kaydale** [comment]
screen shot 2017-03-20 at 14 59 38
Loading page has the banner at the bottom about switching LA but none of the other pages do. Not sure if that was intentional or not?

**Comment by kaydale** [comment]
clicking continue on http://localhost:3000/service-patterns/concessionary-travel/example-service/good-photo results in this error: 
screen shot 2017-03-20 at 15 01 03

**Comment by suryanaga** [comment]
- Fixed the Get help link
 - The council picker footer is on all the pages
 - The template not found error is already in master, it's a bug with the council picker. You need to refresh the page to get it to work.

**Comment by suryanaga** [comment]
@kaydale Ok that last thing should be properly fixed now.

**Comment by anthonylord** [comment]
- [ ] Has this journey been researched yet? I'm wondering that when a user doesn't have a photo, do we need to add 'phone' or 'smartphone' whenever we talk about a 'digital camera'? Most users will have a phone that they can use to take a photo, but may not realise this as it sounds like they can only use a 'proper' digital camera.

- [x] When a user says they don't have a photo, the following 2 pages have the same H1, so 3 pages have the same H1. When it comes to accessibility, I don't think that's good practice, all H1s need to be different?

- [x] Change the H1 'You’ll need to get a digital photo from a shop' to 'You need to get a digital photo from a shop'

- [x] If a user goes through the non-Verify digital route, will they also see the 'You need to get a digital photo from a shop' page? If so, the Verify message on this page should be removed. Otherwise try this Verify message: 'You'll need to restart your application for an older person's bus pass. You do not need set up GOV.UK Verify again, just sign in with your certified company.'

- [x] Update 'If you need help doing this, you can contact the council.' to 'If you need help with getting a digital photo, contact Argleton County Council.'

**Comment by suryanaga** [comment]
This is being merged into the prototype, which is going into research. So all of these changes you're looking at are pre-research essentially.

 - I'll leave the point about the camera as it is for now and see how it tests.
 - I wasn't aware about the h1 point, makes sense though. What do you suggest for the h1s of those pages?

**Comment by anthonylord** [comment]
Cool, looking forward to seeing the research findings.

When the page has a question, the H1 can be the question, like on Register to vote: https://www.gov.uk/register-to-vote. So 'Do you have a digital camera' is the H1. 
As for the other page, not sure what the H1 could be. Something about steps as there are 2 numbered steps on the page

**Pull request merged**
