### PR TITLE
Changes to asking for contact info for notifications in ConTravel

### LINKED ISSUE #102: CT: If there are manual checks involved, collecting contact information to notify user of progress
We should only collect contact information if the application requires manual checks.

If we are using an automated photo checker then we should be able to confirm the application success and give a date they should receive their pass by immediately.

If we cannot use an automated photo checker then the collection of contact details should come after the photo upload stage, before the confirmation page.

### PR DESCRIPTION
**Pull request by suryanaga**
Fixes #102.

Swapped the order of 9 & 10 on the pattern page and in the journey flow and also revised some of the content on the page asking for the details so it makes more sense, including also the option to not be notified if the user doesn't want to.

screen shot 2017-02-06 at 17 34 25
screen shot 2017-02-06 at 17 34 00

### CODE REVIEW

**Comment by suryanaga** [comment]
Hey @kateiw - you able to review this? Can assign to @kaydale if not.

**Comment by suryanaga** [comment]
@kaydale conflicts fixed

**Comment by kaydale** [comment]
@sanjaypoyzer 

screen shot 2017-02-20 at 12 49 04


This line about confirmation email, is that still appropriate? Would it be not be better to send a confirmation to the users preferred channel?

**Comment by kaydale** [comment]
@sanjaypoyzer When you try to click the link "See the example page telling the user when they can expect to receive their pass" 

I get this error: https://drive.google.com/open?id=0B5wEPxglOrqoNkR5ZjRobW9LODQ

**Comment by suryanaga** [comment]
@kaydale Please show the URL of pages, rather than just a partial screenshot... I have no idea what page that is.

**Comment by suryanaga** [comment]
Ah ok found the page, don't worry. I think in this context it makes sense for it to be an email. I'm not sure people usually sign up for a confirmation text.

**Comment by suryanaga** [comment]
Link in the video should work now

**Pull request merged**
