### PR TITLE
Ability to change which council you are testing with

### PR DESCRIPTION
**Pull request by suryanaga**
Another big one. Addresses #139.

screen shot 2017-02-15 at 16 05 39
screen shot 2017-02-15 at 16 05 45
screen shot 2017-02-15 at 16 05 59

Will add in instructions for how to add council variables and a council stylesheet in a future pull request. This one just adds the ability to switch, which is stored in the session.

@kaydale Would particularly appreciate feedback on where I could link to the council picker page.

### CODE REVIEW

**Comment by kaydale** [comment]
screen shot 2017-02-16 at 09 08 33

When you get to verify land in the unbranded prototype if still reads as if it is Argleton

**Comment by kaydale** [comment]
screen shot 2017-02-16 at 09 13 26

screen shot 2017-02-16 at 09 13 43


@sanjaypoyzer 
Ahhh so when I went through the success verify path it sent me back to Argleton was it supposed to do that?

**Comment by kaydale** [comment]
screen shot 2017-02-16 at 09 15 31


Just to show that I did select unbranded council - and it worked prior to hitting the verify prototype

**Comment by suryanaga** [comment]
@kaydale Ah yes, good catch. I need to add a variable in the link to Verify, and also need to set up the unbranded council on the stable prototype. I'll need to remember to set up the councils on the Verify prototype as well when they add their own.

**Comment by suryanaga** [comment]
@kaydale conflicts fixed

**Comment by kaydale** [comment]
So are you still working on all the other stuff @sanjaypoyzer

**Comment by suryanaga** [comment]
@kaydale Which other stuff?

**Comment by kaydale** [comment]
@sanjaypoyzer https://drive.google.com/open?id=0B5wEPxglOrqoY05kaGtlaVJCRWc

Video showing how unbranded prototype doesn't work.

**Comment by suryanaga** [comment]
@kaydale Ok I think I've fixed the issue, and also put it all on one page which makes it a lot more usable. I also added Argleton as the default because it was breaking before users picked a council.

screen shot 2017-02-20 at 12 25 15
screen shot 2017-02-20 at 12 25 24

**Comment by kaydale** [comment]
@sanjaypoyzer 
on this page: /council-picker
"change council" button does not link

**Comment by suryanaga** [comment]
@kaydale Works on my machine :/

**Comment by kaydale** [comment]
@sanjaypoyzer 
So I figure out what happened - you will see in the video that unbranded works but I just didn't get how to navigate to the service start. I think before this if you clicked "Change council" it would go directly to https://verify-local-patterns.herokuapp.com/ and continue as unbranded. 

Video is here: 
https://drive.google.com/open?id=0B5wEPxglOrqoY05kaGtlaVJCRWc

**Comment by suryanaga** [comment]
@kaydale That works as expected. What were you expecting to happen?

**Comment by kaydale** [comment]
@sanjaypoyzer 
Also realised its still sending Argleton across when it gets to the verify prototype 
screen shot 2017-02-21 at 09 25 04
Will that work ok when its merged?

**Comment by suryanaga** [comment]
@kaydale Ok that should all work now!

**Comment by suryanaga** [comment]
@kaydale Just had a little go at doing an error message for if the council picked is already chosen (which is the thing you were doing) but it's pretty complicated and requires quite a bit of rewrite, so I'm going to leave it for now as this feature only has a few users right now. (ie The people facilitating usability testing in councils.)

**Comment by kaydale** [comment]
@sanjaypoyzer 

Works better but still links though to argleton branded confirm address page

https://drive.google.com/open?id=0B5wEPxglOrqoNWRFUTFIUzVIcUE

**Comment by suryanaga** [comment]
@kaydale Yep, that's because it has to link back to the deployed version. In other words, that should work once it's merged.

**Comment by suryanaga** [comment]
screen shot 2017-02-21 at 11 26 05

giphy 2

**Pull request merged**
