### PR TITLE
Add Camden to list of councils in prototype

### PR DESCRIPTION
**Pull request by Josh--M**
Added a Camden template and .scss, and updated the councils.json list

### CODE REVIEW

**Comment by suryanaga** [comment]
@Josh--M Thanks for this Josh - It's looking really good. There's a few more things though that could be copied from Camden's website to make it look more realistic. Let me know if I'm wrong, but as I understand it the new live service would include:

 1. The header
 2. The sidebar (headed "Transport and Streets" in below screenshot)
 3. The footer section
 4.  The related information section, just above the footer 

Particularly for the header, an image would be fine (or a couple images for different screen sizes). We just need the user to be having a realistic experience so we can see what they do and if they want to click on anything outside of the service content.

## Screenshot of Camden's current website

screenshot-camden gov uk 2017-04-05 15-18-42



## Screenshot of current localisation

screenshot-localhost-3000 2017-04-05 15-17-30

**Comment by Josh--M** [comment]
Hey @sanjaypoyzer 

Fair question. The main camden.gov.uk website does use the extended header, left-hand navigation, related information, and extended footer. This is for main content. **Service transaction** pages however are more streamlined - using a smaller header and footer, and no content links (sidebar and related info) outside what's on the page itself.

For example:

image

image

So basically I've gone for the service transaction template here. I've just added a couple more changes, to tidy the footer link, and to reflect the fixed-width layout that's used.

Does that make sense / seem okay?

**Comment by Josh--M** [comment]
Also @sanjaypoyzer : not sure whether it's worth raising an issue for, but when returning from the Verify prototype I was being kicked back to the service start page (with Argleton style selected), instead of the 'Verify says this is your date of birth - is that correct?' page (can't double-check this at the moment as the IDP prototype is non-responsive right now). 

Is there anything you need to do on your end to enable camden-concessionary-travel as a return path?

**Comment by suryanaga** [comment]
@Josh--M Ah ok, thanks for clarifying that. In that case it's ready to merge!

Link back should work now it's merged, it's because the verify prototype links back to the hosted prototype rather than your local instance.

**Comment by Josh--M** [comment]
Nice, thanks @sanjaypoyzer ! 👍 

Minor thing: still having a routing issue when returning from Verify (this is even when using the hosted prototype, not my local instance).

After the 'checking details' screen (https://govuk-verify.herokuapp.com/wait-for-match?action=sign-in&requestId=concessionary-travel-camden), I expect to end up on the 'confirm DOB' screen (https://verify-local-patterns.herokuapp.com/service-patterns/concessionary-travel/example-service/confirm-dob). 

However, I am taken right back to the start page (https://verify-local-patterns.herokuapp.com/service-patterns/concessionary-travel/example-service/start-page).

Interestingly, the expected path **does** work if I insert other council names into the URL eg: 
- https://govuk-verify.herokuapp.com/wait-for-match?action=sign-in&requestId=concessionary-travel-argleton
- https://govuk-verify.herokuapp.com/wait-for-match?action=sign-in&requestId=concessionary-travel-buckinghamshire
^requesting either of these will redirect to the 'confirm DOB' screen (with the Camden styling applied)

I can fudge it for demo/testing by just loading the 'Confirm DOB' screen in a separate tab, but it's a bit jarring. Any ideas what might be causing it? (a mapping somewhere?)

**Comment by suryanaga** [comment]
@Josh--M Gah sorry, yes that was my fault. I didn't add Camden with the others and then when I did yours the other day I did it in a bit of a rush. Works properly now.

**Comment by Josh--M** [comment]
No prob, all good now. Cheers!

**Pull request merged**
