### PR TITLE
PR: Changing sub-header on CT start page

### PR DESCRIPTION
**Pull request by lizziebruce**
Following UR on #458 making sub-header instructional/task-orientated to encourage users to read section.

Before 
screen shot 2017-05-22 at 15 49 39

After
screen shot 2017-05-22 at 15 49 23

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Looks fine, is this the sort of thing we need to do reviews for?

**Comment by lizziebruce** [comment]
@samuelculley good question!

**Review by suryanaga — APPROVED** [review]

**Comment by suryanaga** [comment]
+1, we don't need a review or a pull request for a change this small -- Let's just put the issue number in the commit message so the commit shows up on the issue

**Comment by lizziebruce** [comment]
@sanjaypoyzer  ^^^ does that mean we can do a commit on the master for this sort of change?

**Pull request merged**
