### PR TITLE
PR: Add page for DVLA API lookup

### PR DESCRIPTION
**Pull request by suryanaga**
## Addresses #145: Some councils need some extra information about the user's vehicle for enforcement purposes.

We need users to show all the data that we are looking up, in order to comply with our privacy principles.

This is a council option. Some councils do not do look up or use this extra information. Councils who do not have the DVLA API turned on in their council options, will have the same  body content as the 'Before' screenshot below and will also skip the vehicle details page.

**Before**
image

**After**

With no DVLA API:
image

With DVLA API: 

image

**New page**
screen shot 2017-05-16 at 15 00 11

### CODE REVIEW

**Review by lizziebruce — CHANGES_REQUESTED** [review]
For councils receiving the "Before" content:
1. full stop needed after vehicle
2. current prototype has "You've chosen 1 resident's parking permit." as first copy line.
3. current prototype has 'enter your vehicle's registration 
number' in header font
4. privacy line missing (but assume when this is merged into the master this will update)

For councils receiving the "After" content:
5. add colon after "to" i.e. "We need your vehicle's registration number to:"
6. as above, current prototype has "You've chosen 1 resident's parking permit."
7. privacy line as above

**Comment by suryanaga** [comment]
@lizziebruce Sorry, those screenshots were out of date which was confusing on top of there being two different versions to review. Should be all up to date now.

Have also added the colon 👍

**Review by EUzkuraityte — APPROVED** [review]

**Review by lizziebruce — APPROVED** [review]

**Comment by suryanaga** [comment]
Adding @samuelculley to QA

**Comment by lizziebruce** [comment]
@sanjaypoyzer If there's an enter V5C details page, would that come after the new DVLA confirmation page, or is it never the case that both would occur in the same journey?

**Comment by suryanaga** [comment]
@lizziebruce There's potentially a need for both as they do different things (DVLA gives councils details needed for enforcement, V5C proves ownership). In the case of both being there, yes V5C will come after the confirm vehicle details page.

**Comment by lizziebruce** [comment]
@sanjaypoyzer thanks. I realised they do different things. Have put V5C after confirm vehicle details on journey map.

**Review by ghost — APPROVED** [review]
Looks good, no issues with process!

**Pull request merged**
