### PR TITLE
PR: Handling people who've recently moved

### PR DESCRIPTION
**Pull request by suryanaga**
Addresses #211.

There are 4 potential cases of addresses being returned from Verify:

## 1. Council receives the most recent **verified** address and it is in the right area
Obviously this is the best case scenario. In this case users are definitely eligible for a resident's parking permit.

This PR includes a slight alteration to the content of the "confirm address" page.

### Before
image

### After
image

If users answer "No" on this page, councils can handle this the same as receiving an unverified address. (See '3' below.)

## 2. Council receives an **unverified** address which is in the right area
Councils should basically ignore unverified addresses. Only some IDPs will actually send this information, but in any case it's not information that the council can trust as it's not proven in any way. Whenever this happens, 3 will happen as well, so councils should just act as if 3 has happened. 

## 3. Councils receive an address which is not in the right area.
In this case, Verify has not proven that the user is eligible for a parking permit. Users should enter their new address (screenshots below) and then the councils can handle this in 4 different ways:

 - A. Councils check the entered address hasn't exceed it's allowance for permits, and then issues users a 3 month temporary permit, telling them to re-apply in 3 months. (This option comes with added assurance if using LOA2 as councils can tell the user they can be taken to court if they lie.)
 - B. Users upload a document to prove their address, such as a landlord's agreement or proof of buying the property (sometimes called 'register of title' apparently)
 - C. Use V5C as proof of address, to be uploaded later on in the user journey
 - D. Councils use another form of locally held data to prove address, such as council tax number

Ok, now for the screenshots...

In all options (A, B, C, D), when councils receive an unverified address, users should see these two pages:
image

screenshot-localhost-3000 2017-05-18 14-45-13

If councils have chosen option A, then the next screen should tell them about temporary permits:
image

## Final page

There is 6 different versions of this page. That's because there's two different routes (3 month and Full 6/12) and a bunch of different options for councils to choose in each of those two different routes.

### 1. User is getting a 3 month permit and Council allows user to write their own 3 month permit
screenshot-localhost-3000 2017-05-23 15-53-44

### 2. User is getting a 3 month permit and Council allows user to print their own temp permit
screenshot-localhost-3000 2017-05-23 15-55-02

### 3. User is getting a 3 month permit and Councils only allow permits via post. User must wait for 3 month permit.
screenshot-localhost-3000 2017-05-24 11-16-12

### 4. User is getting a Full permit (6/12 month) and Council allows user to write their own permit whilst they wait.
screenshot-localhost-3000 2017-05-24 11-47-37

### 5. User is getting a Full permit (6/12 month) and Council allows user to print temp permit whilst they wait.
screenshot-localhost-3000 2017-05-24 11-44-32

### 6. User is getting a Full permit (6/12 month) with no temp permit
screenshot-localhost-3000 2017-05-24 11-42-30

## To Do 
- [x] Make sure rest of the journey for temporary permits makes sense (i.e reflects 3 months)
- [x] Add 3 options for temporary permit: Printable, writable, and postal
- [ ] Add the extra screens for B, C, and D
- [ ] Add all of the above to the pattern text

### CODE REVIEW

**Comment by suryanaga** [comment]
@lizziebruce @EUzkuraityte Before I delve into adding the extra cases talked about above, could you both read over what I've done so far? 

Lizzie, I imagine you'll probably have a bit of feedback, especially on that last screen!!

**Comment by EUzkuraityte** [comment]
@sanjaypoyzer As a concept this looks ok to me, but a couple of things:
1 - the temporary 3 month permit should be posted to the address without the option to print it
2 - user should have the option to bring in docs in person if LAs allow

**Comment by suryanaga** [comment]
@EUzkuraityte Agreed on 2, but if the temporary 3 month permit is posted to them, what to they do whilst they are waiting to receive it?

**Comment by EUzkuraityte** [comment]
@sanjaypoyzer They'll just have to deal with it. It's a massive fraud risk issuing a temporary permit to someone who's address we cannot confirm. We can suggest the user to do B, C or D if they want a permit now. Either way, I'd say tag all LA contacts to the comment and see what they have to say about this. It very much depends on their risk appetite...

**Comment by suryanaga** [comment]
@EUzkuraityte I think "massive fraud risk" is a massive overstatement here. Let's talk through it in person.

**Comment by lizziebruce** [comment]
@sanjaypoyzer Copy edit for the New resident permits screen para 2. This isn't a finished/polished version but hopefully clarifies a couple of things. NB not sure if credit history is the correct term.

> You can still apply for a temporary resident’s permit, which expires in 3 months. Shortly before it expires, re-apply for the 6 or 12 month resident’s parking permit – by that time, GOV.UK Verify should be able to verify your address, as there will be a credit history for you at the new address. 

For option B I think it's tenancy agreement for rental and for buying we should probably offer a range of things like Memorandum of Sale, Mortgage agreement, Register of title (which is at Land Registry and happens after you complete i.e. after you move in), leasehold/freehold agreement (also get after you move).

**Comment by EUzkuraityte** [comment]
@sanjaypoyzer ok! I'm off tomorrow and on Mon, but any other time I'm happy to do it

**Comment by lizziebruce** [comment]
^^ let me know the outcome, I can provide copy for option(s) taken forward

**Review by lizziebruce — APPROVED** [review]
One question: for
"All your permits will be 3 month temporary resident permits." is this for 3 or more? If not it should just be "Your permits will be 3 month temporary resident permits." i.e. without the word "All".

**Review by lizziebruce — APPROVED** [review]

**Review by lizziebruce — APPROVED** [review]

**Review by lizziebruce — APPROVED** [review]

**Review by lizziebruce — APPROVED** [review]

**Review by lizziebruce — CHANGES_REQUESTED** [review]
Don't use "In the mean time" as it's not plain English. Suggest "Until then" or "While you wait" (need to see the context for this).

**Review by lizziebruce — APPROVED** [review]

**Review by lizziebruce — APPROVED** [review]

**Review by lizziebruce — APPROVED** [review]

**Review by lizziebruce — APPROVED** [review]
TBH I don't know what I'm approving here but trust that it's fine!

**Review by lizziebruce — APPROVED** [review]

**Review by lizziebruce — APPROVED** [review]

**Comment by lizziebruce** [comment]
👍

**Review by lizziebruce — APPROVED** [review]

**Review by lizziebruce — APPROVED** [review]

**Comment by suryanaga** [comment]
@lizziebruce @EUzkuraityte Ok I think I've got all the different versions - 6 in total - of the last page. Have a look at the screenshots above and let me know if I've missed any cases.

I'm going to add an extra feature to the prototype so that we can feed it data via a URL, so instead of having to click through the whole journey to get to the screen with 3 month permits, you'll just add `?unverifiedAddress=true` to the URL. That'll make it easier to link to screens as we talk about them in the future. 

All those 6 screenshots are just regarding how councils issue 3 month permits and temporary permits. I haven't yet started on the other options for dealing with unverified addresses (labelled B, C and D above.)

**Comment by lizziebruce** [comment]
Hi @sanjaypoyzer these look good to me & logic makes sense. Just 2 points from me. On screenshots 1. 2. and 3. the copy on third step probably needs to change, as it's a case of reapplying for a 6/12 rather than renewing the 3 monther. Also changed it to say "shortly before" as it'll take them time to reapply rather than getting an automatic renewal.

Before
screen shot 2017-05-24 at 12 04 20

After

> 3. Reapply for a 6 or 12 month parking permit shortly before your 3 month short-term permit expires. GOV.UK Verify should by then be able to verify your new address.

My other point is about something that might be a known bug, the "6/12 months" isn't showing on that same piece of copy for screenshots 4. 5. 6.

screen shot 2017-05-24 at 12 12 27

**Review by lizziebruce — CHANGES_REQUESTED** [review]
I've made content change suggestions/bug flag for the third ol bullet on all screenshots via my last comment on this issue

**Review by lizziebruce — APPROVED** [review]

**Review by lizziebruce — APPROVED** [review]

**Comment by suryanaga** [comment]
@lizziebruce The latter point is just because I didn't step through and choose 6 or 12, and there isn't a default value set so it shows nothing there.  Will make the other change.

**Comment by EUzkuraityte** [comment]
Hi @sanjaypoyzer looks good to me, the only things to consider are:
1 - I assume that LA application confirmation number will be different from the temporary permit number (based on my previous experience working for a LA), which is why I think we should anticipate that LAs will have to change the content a little. Happy to keep this in the prototype just in  case some can issue the same application and temporary permit number, but wanted to flag this with you
2 - our success pages screenshots cover the option for when a user applies for 1 permit only. Will this get automatically adjusted for multiple permits?

**Review by lizziebruce — APPROVED** [review]

**Review by lizziebruce — APPROVED** [review]

**Review by lizziebruce — APPROVED** [review]

**Comment by lizziebruce** [comment]
Copy for unverified address page title, as per discussion this morning. @sanjaypoyzer @EUzkuraityte 

Before (screenshot of a screenshot)

screen shot 2017-06-07 at 14 17 48

After (options)
A

> Verified address not in Argleton City Centre

B

> Verified address not eligible

C

> Verified address outside requested parking area

D

> Address not in parking area


Plus new copy for the line at the bottom of the screen:

> This address is not in Argleton City Centre, where you're applying for a resident's parking permit. You need to tell us your current address.

**Comment by lizziebruce** [comment]
@EUzkuraityte 

Narrowed it down to these two options, and we've gone with the second one for clarity:

Verified address outside requested parking area
Verified address not in Argleton city centre

**Review by lizziebruce — APPROVED** [review]

**Comment by suryanaga** [comment]
I'm going to merge this in now as the branch now contains the route for getting a 3 month permit. 

I'm going to do another pull request tomorrow with the route for uploading proof of address.

**Pull request merged**
