### PR TITLE
Make upload buttons nice and get photo upload ready for lab testing

### PR DESCRIPTION
**Pull request by suryanaga**
This PR focusses on the bits of both services that require documents to be uploaded, and gets them ready for testing in the lab. No files are actually uploaded (as it's just a prototype) but the prototype should respond to you uploading them, so do test that that works.

###  Add proof of address (nonverify route)

**Before** 
screen shot 2017-02-22 at 17 53 29
(User then had to pick file, and then click 'Next')

**After**
screen shot 2017-02-22 at 17 55 40
screen shot 2017-02-22 at 17 55 57
screen shot 2017-02-22 at 17 56 03
screen shot 2017-02-22 at 17 56 05

# Concessionary Travel

## Add proof of address and proof of age

Looks exactly the same as above. Clicking through the nonverify route should work fully.

## Upload photo

Have removed the step through photo guide so we can test for what issues users have without the guide. Plus:

**Before**
screenshot-localhost 3000 2017-02-23 09-55-47

**After**
screenshot-verify-local-patterns herokuapp com 2017-02-23 09-55-20

### CODE REVIEW

**Comment by suryanaga** [comment]
@kaydale That was a fast review!

**Comment by suryanaga** [comment]
Forgot to mention that this addresses #166 & #133

**Comment by kaydale** [comment]
@sanjaypoyzer I think I was reviewing it before you actually put me down as a reviewer

**Comment by suryanaga** [comment]
@kaydale On the ball!

**Pull request merged**
