### PR TITLE
make permit price consistent throughout

### LINKED ISSUE #218: inconsistent pricing info throughout
Hi @sanjaypoyzer it's a minor thing, but on the [service start page](https://verify-local-patterns.herokuapp.com/service-patterns/parking-permit/example-service/start-page) we give price ranges for £51, £81 and £153, while later on the user can choose between paying £21.50 and £51 and where the user confirms payment details it says £60

### PR DESCRIPTION
**Pull request by suryanaga**
Fixes #218.

 Pages affected:

- /pre-payment
- /permit-price
- /enter-card
- /confirm-card-payment

### CODE REVIEW

**Comment by kaydale** [comment]
@sanjaypoyzer 
When you go through this and come to the confirmations screen I think it skips the renewal notification step... 
https://drive.google.com/open?id=0B5wEPxglOrqoNmJucFJUMWJ3V28

**Comment by suryanaga** [comment]
@kaydale That's because you've only just merged that into master, and not merged master or that branch into this one yet

**Comment by kaydale** [comment]
@sanjaypoyzer I've merged it now but its still broken...

**Comment by suryanaga** [comment]
@kaydale that screenshot doesn't work

**Pull request merged**
