### PR TITLE
add option for user to get multiple permits (no pre-existing permits in the household)

### LINKED ISSUE #224: Users need to apply for multiple resident's permits at the same time
**Impact:** Users wanting to apply for multiple passes would have to complete multiple applications.

**Evidence:** Some users reported past applications for multiple permits and for some this remained an issue and a concern throughout the transaction.

### PR DESCRIPTION
**Pull request by suryanaga**
Fixes #224.

Massive thanks to @tunylund for making this actually work!  🎉

---

## Logic:

<details>

code2flow_49711

</details>

### Resident start page

screenshot-localhost-3000 2017-04-10 11-51-31

screenshot-localhost-3000 2017-05-08 14-23-40

### Eligible page

screenshot-localhost-3000 2017-04-10 11-52-17

screen shot 2017-05-08 at 14 24 41

## New page added:

 - How many resident permits?

screenshot-localhost-3000 2017-04-10 11-53-10
screen shot 2017-05-08 at 14 27 07

If council allows more than 7 permits, then radio buttons become a free choice field. Cambridgeshire is currently the only council which allows this many permits. (They allow unlimited permits.)

screenshot-localhost-3000 2017-04-10 11-55-02

### enter-reg
screenshot-localhost-3000 2017-04-10 11-59-11

### permit start date

("qwerty" etc is the registration numbers I entered)
screenshot-localhost-3000 2017-05-08 14-32-39

### permit length

also moved this page to after the permit start date page, feels more natural there

screenshot-localhost-3000 2017-05-08 14-35-26

### pre-payment

screenshot-localhost-3000 2017-05-08 14-36-53

The 'Change' links link back to the relevant page in the flow.

### CODE REVIEW

**Review by lizziebruce — CHANGES_REQUESTED** [review]
1. Pre-payment page, change to 6 months 12 months i.e. plural. This is for consistency as the page before has months in plural. We should either say 6 month and 12 month or 6 months and 12 months all the way through.
2. Listed costs page, please change the hyphens to n dashes i.e. – not -. This is for grammar reasons.
3. Listed costs page, I'd remove the work 'costs' as it's implied by the dash and is just adding extra non-unique words, which impedes scanning. Unless users find this confusing would recommend taking the word 'costs' out from the 4 radio button labels.

**Review by EUzkuraityte — CHANGES_REQUESTED** [review]
This looks good - a very good start, but seems to miss out a bit of logic.

The prototype assumes that the household does not have any pre-existing permits so the user is allowed to choose the maximum number of permits allowed. If that's what we want to put into the prototype, then it's fine. We should, however, differentiate between '4 permits' and the '4th permit'.

Otherwise, I'd like to see a version more similar to Cambridgeshire's where we tell the users:

> 1st permit costs x
> 2nd permit costs x
> ...
> 6th permit costs x
> 
> There are [numeric value] existing permits in your household. How many additional permits do you want to apply for?
> [numeric value validation up to 4 minus the number of existing permits]

Also, the price displayed in the common prototype clashes with users needing to know the permit price. i.e. 3 permits might cost £204, but at this point the user is having to work out that they will pay £51 for the 1st and second permits and £102 for the 3rd permit. Pricing rules also need to be fixed as they don't add up.

**Comment by suryanaga** [comment]
@lizziebruce Have made those changes.

@EUzkuraityte 

 - Currently the scope of the prototype is users applying for their first permit. We can change that, but we'll need to change the participants that we're recruiting and testing with. That feature is outside the scope of this pull request I would say.
 - Does the user need to know the rules of how the permit prices are worked out at this point? We have a choice between showing them how to work out the price of the permits, or showing them how much the permits they need will cost. I think the latter is more helpful.
 - The pricing logic is fixed. Sam can QA this further when he reviews.

**Comment by EUzkuraityte** [comment]
@sanjaypoyzer 
1. The user can apply for his / her 1st permit which might not be a household's 1st permit. Assuming a husband has just bought his 1st car and is now applying for his very 1st permit, but his wife (who's always had a car) already got the 1st permit for the household. It means he gets his 1st permit = new application, which is the 2nd permit for the household. This is within the scope of the pilot.
2. I think both are important. Coming back to what user research has taught us is that users ant to know how the price is calculated. 
3. Cool! I only raised it because it's shown incorrectly in the screenshots

**Comment by suryanaga** [comment]
@EUzkuraityte 

1. I didn't say anything about the scope of the pilot - The scope of this pull request is first time applications. The use case you talk about should be opened as a new issue, or this work will be further delayed.
2. We should tell the users how the price is calculated elsewhere. Putting both on this one page would be busy and confusing. The most important need for this page is 'how much will I need to pay'.

**Comment by lizziebruce** [comment]
@EUzkuraityte 
cc @sanjaypoyzer 
1. Was also assuming point of view of a new resident i.e. first ever permit(s)
2. Do users want to know the exact calculations, or content like: "the cost for additional permits will increase after [X] permits"?

**Comment by suryanaga** [comment]
I've not seen any research suggesting users need to know the rules when they're selecting how many permits they need

**Comment by EUzkuraityte** [comment]
@sanjaypoyzer ok! I've changed the title of this issue and will open a new one for the scenarios with pre-existing permits. I'd rather just have one good version that does a postcode look up in the database to find the info and then display accurate info to the user on permits and prices available but in the interest of getting things done I'm happy to give in on this. 

The only thing I ask for is to make the language consistent for all local versions regardless of the number of permits - at this screen for this use case we either say '1 permit costs' or '1st permit costs', '2 permits cost' or '2nd permit costs' etc because they mean different things.

**Comment by suryanaga** [comment]
@EUzkuraityte I don't think they need to be consistent across councils. The best solution is telling people how much they are going to pay. The only reason I've not done that for Cambridgeshire is because we don't know how much they need to pay until they tell us how many they want.

Please both of you change your review status when you're happy with the PR. cc @lizziebruce

**Comment by lizziebruce** [comment]
@EUzkuraityte @sanjaypoyzer as this is kind of a template, I agree we need to pick either '1 permit costs' or '1st permit costs', '2 permits cost' or '2nd permit costs' to do the thinking and reasoning for the councils. 
There are pros and cons to both ways of expressing this. '2nd permit costs X' will highlight the difference in price but only if the user understands correctly – they may think that there is a discount for buying 2 and think 2 cost £61 (using Cambridge costings) in total. It would be easy to misinterpret so I'd recommend: 

1 permit – £51 
2 permits – £112
3 permits – £183

i.e. logic as displayed in the prototype now

**Review by lizziebruce — APPROVED** [review]

**Review by EUzkuraityte — APPROVED** [review]

**Review by ghost — CHANGES_REQUESTED** [review]
The calculations for permit prices aren't behaving consistently:

1. The prices shown below are only for permits of 12 month length, can this be changed to account for different permit lengths

image

2. The total calculation isn't accurate - I can't work out the logic here, I've not been able to get a correct total with any combination of pass lengths. If I go back and forth, changing how many cars I want, this gets worse and it implies I still want to buy 3 permits even though I've changed to just one car. 

image

image

**Review by lizziebruce — APPROVED** [review]

**Comment by suryanaga** [comment]
@samuelculley 

1. is now done:

image


@tunylund Could you take a look at the bug Sam is talking about above? Looks like the total amount isn't being calculated correctly.

**Comment by lizziebruce** [comment]
@sanjaypoyzer @petegale @EUzkuraityte when I look at this page, my eyes go straight to the byline, "Your council can have a maximum of 4 resident's parking permits." I remember a few users in UR were skipping the h1s too. Could we try dropping the h1 by a line break or two on the question pages to see if this stops happening? Is it possible to include eyetracking in the next UR sessions please?

**Comment by EUzkuraityte** [comment]
@lizziebruce I don't mind either way, but agree that it would be good to have eyetracking

**Comment by EUzkuraityte** [comment]
@lizziebruce @sanjaypoyzer Should multiple permit page specify that the user can apply for their cars only and not on behalf of someone else? i.e. a mother cannot apply for 4 permits and get one for herself, one for her two kids and one for hr husband.... or do you think this is implied?

**Comment by suryanaga** [comment]
@lizziebruce Re: Users not reading H1s - Let's record that as a separate issue and gather evidence for it there.

**Comment by suryanaga** [comment]
@EUzkuraityte The thing about the cars having to be owned by you only applies for the councils are asking for a V5C. I'll add that as conditional content if that council option is selected.

**Comment by suryanaga** [comment]
If V5C scan or enter number option is turned on:

image

**Review by lizziebruce — APPROVED** [review]

**Comment by EUzkuraityte** [comment]
@sanjaypoyzer @lizziebruce 
hm... the user does not have to be the owner of the vehicle, they have to be the keeper (or main user) of the vehicle and also even if the councils aren't asking for V5 they still apply the same rules - the user can apply for their car

**Comment by suryanaga** [comment]
@EUzkuraityte If the council is not asking for the V5C, then how do they know the user is the "keeper" of the vehicle?

**Review by ghost — APPROVED** [review]

**Comment by suryanaga** [comment]
Great! Thanks @tunylund for fixing that bug! 

And thanks for @samuelculley, @lizziebruce and @EUzkuraityte also for checking over it too! 

# 🎉

**Comment by lizziebruce** [comment]
Re owner/keeper/main user. A key GOV.UK principle is using language users understand. We could say:

> the person who's responsible for the vehicle(s), as stated on your V5C document(s).

or

> the main user of the vehicle(s), as stated on your V5C document(s).

We can still reference the V5C documentation even if the user not required to upload it.

**Pull request merged**
