### PR TITLE
Adds content to Start page to show users how price is determined and when free

### PR DESCRIPTION
**Pull request by lizziebruce**
Copy solution for issues #313 and #297 and small tweaks to reduce/simplify existing copy

Before
screen shot 2017-05-08 at 11 38 06

After
screen shot 2017-05-08 at 11 50 56

### CODE REVIEW

**Comment by suryanaga** [comment]
@lizziebruce @EUzkuraityte As I understand it, Blue Badge holders will use a different service to apply for their parking permit. Is this correct?

**Comment by suryanaga** [comment]
@lizziebruce I'm a little unsure about adding content on this page about how the price is calculated. The user need for this page is "I need to know if I need a permit". Getting the user to think about how the permit cost is calculated at this stage seems like a blocker to meeting that user need. I think this information is better placed once the user knows they actually need a permit in the area where they want to park, i.e On the 'Resident's start page'.

**Comment by lizziebruce** [comment]
@EUzkuraityte @sanjaypoyzer 
If separate application for Blue Badge, suggest take out Blue Badge bullet and add sub-heading for Blue Badge with link to relevant service or put in a 'You can also' section like with Bus Pass. The Free permits section needs to be updated by @lizziebruce to include the conditions shown in the 'when does a user not have to pay' council survey screenshot in #313 and resolve #297.

**Comment by EUzkuraityte** [comment]
@lizziebruce to your earlier Q - yes, blue badge applications are separate

**Review by suryanaga — CHANGES_REQUESTED** [review]
- [ ] Move content to Resident start page

**Comment by lizziebruce** [comment]
@sanjaypoyzer this was to resolve #313 but yes it doesn't need to be placed on this page, it's come about from my initial lack of clarity that the service is for all parking permits, not just resident's. As a newcomer it seemed like we had 2 Start pages! 

However, if the first page will be also be the first page for other permits applications (IRL, beyond the prototype) we should consider adding copy to outline different permits you might need, like:

-Resident's and visitor parking permits
-Business and trade parking permits
-Blue and green disabled permits
-Other permits and parking

This may not have come up as an issue in UR as the recruited users were for resident's parking. 

For clarity, the journey we are developing end to end in the prototype is resident's and visitor parking permits – is this correct? As mentioned this morning, it would be really useful for me to have a line sketch of the end to end journey with all the variables and branches. I think @EUzkuraityte offered to draw something up for @sanjaypoyzer to check?

**Comment by suryanaga** [comment]
@lizziebruce Yes, I think some content describing what permits users _might_ need would be useful on that initial start page. I think that will make it clearer to everyone what that page is for as well.

**Review by EUzkuraityte — APPROVED** [review]

**Pull request closed without merging**
